### ISSUE TITLE
Mr_Stickman won't work

### ISSUE THREAD

**Issue by MvE09** [MvE09/Mr_Stickman-game-from-Python-for-Kids-Jason-R.-Briggs1#1]
Look in the code repository for more information, please help!

**Comment by SeraphWedd** [comment]
Under the coords class, only the __init__ is included as an internal function. All the following functions (collide_left, etc) that doesn't have a (self) within their declaration should be moved one tsb behind.

**Comment by MvE09** [comment]
Thanks! I got it almost working properly now! The stick figure is now executing the commands properly. The only problem now is that it is moving/reacting very slowly. It takes the stick figure about one second to adjust three pixels. Any ideas about that?

**Comment by MvE09** [comment]
No worries! I fixed it! I needed to change an indentation with the mainloop. Thank you very much for your help!

**Comment by SeraphWedd** [comment]
You're welcome~! If this issue is completed, you can close it. I also created a default pygame build, a backbone code, for handling events procedurally. If you're interested, you can maybe take a look~!
